version: '3'
volumes:
  apps:

services:
  studio-frontend:
    build: .
    image: geobretagne/mviewer-studio-frontend
    ports:
      - 8080:80
  studio-backend-python:
    build: srv/python/
    image: geobretagne/mviewer-studio-backend-python
    volumes:
      - "apps:/home/apprunner/store/apps"
  mviewer:
    image: nginx:1.17
    ports:
      - 8081:80
    volumes:
      - "apps:/usr/share/nginx/html/apps"
      - "../mviewer:/usr/share/nginx/html"
