version: '3'
volumes:
  apps:

services:
    # Left as an exercize to the reader :-)
    #  studiobackend-php:
    #    build:
    #        context: ./
    #        dockerfile: Dockerfile-php-backend
    #    image: mviewer/studio-backend:php-latest
    #    volumes:
    #      - "apps:/home/apprunner/store/apps"
    #    ports:
    #      - "5000:5000"
  studiobackend-python:
    build:
      context: .
      dockerfile: Dockerfile-python-backend
    image: mviewer/studio-backend:python-latest
    volumes:
      - "apps:/home/apprunner/store/apps"
    ports:
        - "8000:8000"
  mviewer:
    image: mviewer/mviewer
    ports:
      - "8081:80"
    volumes:
      - "apps:/usr/share/nginx/html/apps"
      - "../mviewer:/usr/share/nginx/html"
