version: '3'
services:
  studio-frontend:
    build: .
    image: mviewer/studio-frontend
    ports:
      - 8080:80
  studio-backend:
    build: srv/python/
    image: mviewer/studio-backend
  mviewer:
    image: mviewer
    ports: 
      - 8081:80

  