version: '3'
volumes:
  apps:

services:

  # Select between the next 2 services the backend you want to use, and adapt
  # the docker/nginx-default.conf configuration accordingly.

  # You cannot use both backends at the same time, and you have to be wary if
  # you switch from one to another, as each come with a custom config.json
  # file.

  # If you want to switch, make sure either you modify the config.json, or
  # reinitialize the docker volume.

 #  studiobackend-php:
 #    build:
 #      context: ./
 #      dockerfile: docker/Dockerfile-php-backend
 #    image: mviewer/studio-backend:php-latest
 #    volumes:
 #      - "apps:/var/www/html/apps"
 #    ports:
 #      - "8081:80"
  studiobackend-python:
    build:
      context: .
      dockerfile: docker/Dockerfile-python-backend
    image: mviewer/studio-backend:python-latest
    volumes:
      - "apps:/home/apprunner/apps"
    ports:
      - "8082:8000"
  mviewer:
    # this image is automatically built in
    # the geobretagne/mviewer github repository
    # See https://github.com/geobretagne/mviewer/pull/236
    image: mviewer/mviewer
    volumes:
        - "apps:/usr/share/nginx/html/apps"
    links:
        - studiobackend-python
#       - studiobackend-php
  mviewer-studio:
      image: nginx:1.17.9
      volumes:
        - "./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf"
      ports:
        - "8080:8080"
      links:
          - mviewer
          - studiobackend-python
#         - studiobackend-php

