version: '3'
volumes:
  apps:

services:
  studiobackend-php:
    build:
      context: ./
      dockerfile: Dockerfile-php-backend
    image: mviewer/studio-backend:php-latest
    volumes:
      - "apps:/var/www/html/apps"
    # Uncomment here and comment the one from python
    # to use the php backend on the host port 8000.
    #  ports:
    #    - "8000:80"
  studiobackend-python:
    build:
      context: .
      dockerfile: Dockerfile-python-backend
    image: mviewer/studio-backend:python-latest
    volumes:
      - "apps:/home/apprunner/store/apps"
    ports:
      - "8000:8000"
  mviewer:
    # this image is automatically built in
    # the geobretagne/mviewer github repository
    image: mviewer/mviewer
    ports:
      - "8081:80"
    volumes:
      - "apps:/usr/share/nginx/html/apps"
      - "../mviewer:/usr/share/nginx/html"
