on:
  push:
    branches:
      - master

jobs:
  build_images:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build containers
        run: |
          docker-compose build
      - name: Logging in docker hub
        uses: azure/docker-login@v1
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'
      - name: push containers
        run: |
          docker-compose push

